maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/main/java/org/apache/maven/scm/provider/git/gitexe/command/AnonymousCommandLine.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/main/java/org/apache/maven/scm/provider/git/gitexe/command/GitCommandLineUtils.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/test/java/org/apache/maven/scm/provider/git/gitexe/command/GitCommandLineUtilsAddTargetTest.java
maven-scm-test/src/main/java/org/apache/maven/scm/ScmTestCase.java

Use an AnonymousCommandLine that won't display password if present.

SCM-764 : Fix clear password displayed in logs

---

maven-scm-providers/maven-scm-providers-cvs/maven-scm-provider-cvsjava/src/main/java/org/apache/maven/scm/provider/cvslib/cvsjava/util/CvsConnection.java

http://hg.netbeans.org/releases/file/91d6c4c73bea/lib.cvsclient/src/org/netbeans/lib/cvsclient/command/GlobalOptions.java#l467

[SCM-863] fix NPE in GlobalOptions.setCVSRoot(null) with newer cvsclient

---

maven-scm-plugin/pom.xml
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/pom.xml
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/main/java/org/apache/maven/scm/provider/git/jgit/command/JGitUtils.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/main/java/org/apache/maven/scm/provider/git/jgit/command/branch/JGitBranchCommand.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/main/java/org/apache/maven/scm/provider/git/jgit/command/checkout/JGitCheckOutCommand.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/main/java/org/apache/maven/scm/provider/git/jgit/command/diff/JGitDiffCommand.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/main/java/org/apache/maven/scm/provider/git/jgit/command/tag/JGitTagCommand.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/test/java/org/apache/maven/scm/provider/git/jgit/command/checkin/JGitCheckInCommandCommitterAuthorTckTest.java
maven-scm-providers/maven-scm-providers-standard/pom.xml

This required updating various portions to java 7 so I suspect it would make more sense to just upgrade entirely to java 7.

[SCM-884] Raise to last version of java 7 release

---

maven-scm-providers/maven-scm-provider-integrity/src/main/java/org/apache/maven/scm/provider/integrity/Sandbox.java

Hi, just a couple of typos in the javadocs. Not a native speaker, so feel free to suggest changes. Happy to review/edit/commit/rebase changes.
Cheers
Bruno

Fix minor typos in javadocs

---

maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/test/java/org/apache/maven/scm/provider/git/gitexe/command/blame/GitBlameConsumerTest.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/main/java/org/apache/maven/scm/provider/git/jgit/command/JGitUtils.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/main/java/org/apache/maven/scm/provider/git/jgit/command/diff/JGitDiffCommand.java

[SCM-936] close resources

---

maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/test/java/org/apache/maven/scm/provider/git/jgit/command/diff/JGitDiffCommandTckTest.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/test/java/org/apache/maven/scm/provider/git/jgit/command/status/JGitStatusCommandTckTest.java
maven-scm-test/src/main/java/org/apache/maven/scm/ScmTestCase.java
maven-scm-test/src/main/java/org/apache/maven/scm/tck/command/checkin/CheckInCommandTckTest.java
maven-scm-test/src/main/java/org/apache/maven/scm/tck/command/diff/DiffCommandTckTest.java
maven-scm-test/src/main/java/org/apache/maven/scm/tck/command/status/StatusCommandTckTest.java

@rfscholte This PR assumes the actual values are correct and the expected values are wrong where they differ.

[SCM-941] fix path tests

---

pom.xml

[SCM-930] update plexus-utils

---

pom.xml

deps: update to JUnit 4.13.1

---

src/site/xdoc/matrix.xml

link no longer relevant

---

maven-scm-providers/maven-scm-provider-local/src/main/mdo/maven-scm-local-metadata.mdo

[SCM-949] listStyle --> itemsStyle

---

maven-scm-api/src/main/java/org/apache/maven/scm/provider/ScmProvider.java

fix typos in JavaDoc

---

maven-scm-plugin/src/main/java/org/apache/maven/scm/plugin/AbstractScmMojo.java
maven-scm-providers/maven-scm-provider-accurev/src/main/java/org/apache/maven/scm/provider/accurev/command/changelog/AccuRevChangeLogCommand.java
maven-scm-providers/maven-scm-provider-accurev/src/test/java/org/apache/maven/scm/provider/accurev/AccuRevScmProviderRepositoryMatcher.java
maven-scm-providers/maven-scm-providers-cvs/maven-scm-provider-cvs-commons/src/test/java/org/apache/maven/scm/provider/cvslib/command/changelog/CvsChangeLogConsumerTest.java
maven-scm-providers/maven-scm-providers-svn/maven-scm-provider-svnexe/src/main/java/org/apache/maven/scm/provider/svn/svnexe/command/changelog/SvnChangeLogCommand.java

replace deprecated methods

---

pom.xml

clean out broken links to old mail archives 

---

maven-scm-plugin/pom.xml
maven-scm-plugin/src/it/scm-781/pom.xml

https://issues.apache.org/jira/browse/SCM-978

[SCM-978] Upgrade Maven prerequisite to 3.2.5

---

.github/workflows/maven-verify.yml
Jenkinsfile
maven-scm-plugin/src/test/java/org/apache/maven/scm/plugin/UntagMojoTest.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/test/java/org/apache/maven/scm/provider/git/gitexe/command/checkin/GitCheckInCommandNoBranchTest.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/test/java/org/apache/maven/scm/provider/git/gitexe/command/checkin/GitCheckInCommandTest.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/test/java/org/apache/maven/scm/provider/git/gitexe/command/remove/GitExeRemoveCommandTckTest.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gittest/src/main/java/org/apache/maven/scm/provider/git/GitScmTestUtils.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gittest/src/main/java/org/apache/maven/scm/provider/git/command/blame/GitBlameCommandTckTest.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gittest/src/main/java/org/apache/maven/scm/provider/git/command/branch/GitBranchCommandTckTest.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gittest/src/main/java/org/apache/maven/scm/provider/git/command/changelog/GitChangeLogCommandTckTest.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gittest/src/main/java/org/apache/maven/scm/provider/git/command/checkin/GitCheckInCommandTckTest.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gittest/src/main/java/org/apache/maven/scm/provider/git/command/status/GitStatusCommandTckTest.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gittest/src/main/java/org/apache/maven/scm/provider/git/command/tag/GitTagCommandTckTest.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gittest/src/main/java/org/apache/maven/scm/provider/git/command/untag/GitUntagCommandTckTest.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gittest/src/main/java/org/apache/maven/scm/provider/git/command/update/GitUpdateCommandTckTest.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/test/java/org/apache/maven/scm/provider/git/jgit/command/remove/JGitRemoveCommandTckTest.java

Signed-off-by: Olivier Lamy <olamy@apache.org>

Some Git tests hang when gpg sign activated globally and activte TCK testing for CI

---

maven-scm-client/pom.xml
maven-scm-providers/maven-scm-provider-local/pom.xml
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-git-commons/pom.xml
maven-scm-providers/maven-scm-providers-svn/maven-scm-provider-svn-commons/pom.xml
maven-scm-test/pom.xml
pom.xml

This fixes build with Java 21 due to using a newer palantir formatter

[SCM-1016] Update maven-parent to 41

---

src/site/apt/index.apt

No longer deprecated but removed

---

maven-scm-client/pom.xml
maven-scm-plugin/pom.xml
maven-scm-providers/maven-scm-provider-hg/pom.xml
maven-scm-providers/maven-scm-provider-local/pom.xml
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/pom.xml
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/pom.xml
maven-scm-providers/maven-scm-providers-svn/maven-scm-provider-svn-commons/pom.xml
maven-scm-providers/maven-scm-providers-svn/maven-scm-provider-svnexe/pom.xml
maven-scm-providers/pom.xml
maven-scm-test/pom.xml
maven-scm-test/src/main/java/org/apache/maven/scm/ScmTckTestCase.java
pom.xml

This one's likely to require a few PRs to untangle fully due to the complexity of the multiple nested projects.

Declare used dependencies

---

.github/ISSUE_TEMPLATE/BUG.yml
.github/ISSUE_TEMPLATE/FEATURE.yml
.github/ISSUE_TEMPLATE/config.yml
.github/pull_request_template.md
.github/release-drafter.yml
.github/workflows/pr-automation.yml
.github/workflows/release-drafter.yml
.github/workflows/stale.yml
README.md
pom.xml

* Release and milestone created

Enable Github issues

---

maven-scm-plugin/src/main/java/org/apache/maven/scm/plugin/AbstractScmMojo.java
src/site/markdown/authentication.md
src/site/site.xml

Outline the different ways how to configure authentications
Following this checklist to help us incorporate your
contribution quickly and easily:
Note that commits might be squashed by a maintainer on merge.
This may not always be possible but is a best-practice.
A more thorough check will be performed on your pull request automatically.
If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.
To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

Document SCM authentication means

---

maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/main/java/org/apache/maven/scm/provider/git/gitexe/GitExeScmProvider.java

This closes #1278
Following this checklist to help us incorporate your
contribution quickly and easily:
Note that commits might be squashed by a maintainer on merge.
This may not always be possible but is a best-practice.
A more thorough check will be performed on your pull request automatically.
If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.
To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

Git: Observe interactive flag

---

maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/main/java/org/apache/maven/scm/provider/git/gitexe/command/status/GitStatusConsumer.java

Use Charset to remove formal need for RuntimeException

---

maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/main/java/org/apache/maven/scm/provider/git/gitexe/command/changelog/GitChangeLogCommand.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/test/java/org/apache/maven/scm/provider/git/gitexe/command/changelog/GitChangeLogCommandTest.java

whatchanged is deprecated and supposed to be removed in future git versions (https://git-scm.com/docs/git-whatchanged). "log" is semantically equivalent except for different default which are anyhow overwritten in this context (skip merge commits, raw output).
This closes #1310
Following this checklist to help us incorporate your
contribution quickly and easily:
Note that commits might be squashed by a maintainer on merge.
This may not always be possible but is a best-practice.
A more thorough check will be performed on your pull request automatically.
If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.
To make clear that you …

Replace "git whatchanged" by "git log"

---

maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/test/java/org/apache/maven/scm/provider/git/gitexe/GpgTestUtils.java

This is all test code so it's a safe change as long as test pass
starts on #1298

cleanup runtime exceptions
