maven-scm-plugin/src/it/scm-741-validate-scm-url-matches-working-copy/prepare.groovy

This is a simple fix to stop the build from hanging when executing "svn --version".

Change: Added consumeProcessOutput() to stop hang.

---

maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/main/java/org/apache/maven/scm/provider/git/gitexe/command/status/GitStatusConsumer.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/test/java/org/apache/maven/scm/provider/git/gitexe/command/status/GitStatusConsumerTest.java

Before this, `GitStatusConsumer.resolvePath()` and
`GitStatusConsumer.resolveURI()` got into trouble with
files that include spaces.
To reproduce failure condition (in a git repo):
echo "I'll fail" > "some nice file"
git add "some nice file"
git status --porcelain
The output of the `git status` is:
A  "some nice file"
This causes at least
[JENKINS-24686](https://issues.jenkins-ci.org/browse/JENKINS-24686)
downstream.

Correctly strip quotes in GitStatusConsumer

---

maven-scm-providers/maven-scm-provider-hg/src/main/java/org/apache/maven/scm/provider/hg/HgUtils.java
maven-scm-providers/maven-scm-provider-hg/src/main/java/org/apache/maven/scm/provider/hg/command/inventory/HgOutgoingConsumer.java

Without this fix we constantly getting  incorrect warning message in logs during release about the "A different branch than...". I mean that I use a simple named branches at release, they are works but with warnings. Also once I've seen a  NPE in that block but I can't reproduce it and I have no big wish to reproduce. It is faster to fix.

fix incorrect resolving of branch name from HG outgoing changes && NPE in HgUtils.differentOutgoingBranchFound

---

maven-scm-api/src/main/java/org/apache/maven/scm/ScmResult.java
maven-scm-api/src/test/java/org/apache/maven/scm/ScmResultTest.java

This PR addresses https://issues.apache.org/jira/browse/SCM-811 by allowing the shared ScmResult in the api module to mask known patterns.  Covers SVN and git patterns (which are the ones impacting us and likely most popular).
Includes simple unit test to validate passwords aren't leaked.

Resolves critical security bug SCM-811

---

maven-scm-api/src/main/java/org/apache/maven/scm/CommandParameter.java
maven-scm-api/src/main/java/org/apache/maven/scm/command/checkout/AbstractCheckOutCommand.java
maven-scm-providers/maven-scm-provider-bazaar/src/main/java/org/apache/maven/scm/provider/bazaar/command/checkout/BazaarCheckOutCommand.java
maven-scm-providers/maven-scm-provider-clearcase/src/main/java/org/apache/maven/scm/provider/clearcase/command/checkout/ClearCaseCheckOutCommand.java
maven-scm-providers/maven-scm-provider-hg/src/main/java/org/apache/maven/scm/provider/hg/command/checkout/HgCheckOutCommand.java
maven-scm-providers/maven-scm-provider-integrity/src/main/java/org/apache/maven/scm/provider/integrity/command/checkout/IntegrityCheckOutCommand.java
maven-scm-providers/maven-scm-provider-jazz/src/main/java/org/apache/maven/scm/provider/jazz/command/checkout/JazzCheckOutCommand.java
maven-scm-providers/maven-scm-provider-local/src/main/java/org/apache/maven/scm/provider/local/command/checkout/LocalCheckOutCommand.java
maven-scm-providers/maven-scm-provider-perforce/src/main/java/org/apache/maven/scm/provider/perforce/command/checkout/PerforceCheckOutCommand.java
maven-scm-providers/maven-scm-provider-starteam/src/main/java/org/apache/maven/scm/provider/starteam/command/checkout/StarteamCheckOutCommand.java
maven-scm-providers/maven-scm-provider-synergy/src/main/java/org/apache/maven/scm/provider/synergy/command/checkout/SynergyCheckOutCommand.java
maven-scm-providers/maven-scm-provider-tfs/src/main/java/org/apache/maven/scm/provider/tfs/command/TfsCheckOutCommand.java
maven-scm-providers/maven-scm-provider-vss/src/main/java/org/apache/maven/scm/provider/vss/commands/checkout/VssCheckOutCommand.java
maven-scm-providers/maven-scm-providers-cvs/maven-scm-provider-cvs-commons/src/main/java/org/apache/maven/scm/provider/cvslib/command/checkout/AbstractCvsCheckOutCommand.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/main/java/org/apache/maven/scm/provider/git/gitexe/command/checkout/GitCheckOutCommand.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/main/java/org/apache/maven/scm/provider/git/jgit/command/checkout/JGitCheckOutCommand.java
maven-scm-providers/maven-scm-providers-svn/maven-scm-provider-svnexe/src/main/java/org/apache/maven/scm/provider/svn/svnexe/command/checkout/SvnCheckOutCommand.java

For `maven-release-plugin` we don't need the whole history, but only the top commit. Using `--depth 1` allows to perform releases much faster on repositories with a long history.
Resolves https://issues.apache.org/jira/browse/SCM-739

[SCM-739] Use shallow clones when cloning a git repo

---

maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/main/java/org/apache/maven/scm/provider/git/jgit/command/JGitTransportConfigCallback.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/main/java/org/apache/maven/scm/provider/git/jgit/command/JGitUtils.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/main/java/org/apache/maven/scm/provider/git/jgit/command/checkout/JGitCheckOutCommand.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/main/java/org/apache/maven/scm/provider/git/jgit/command/list/JGitListCommand.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/main/java/org/apache/maven/scm/provider/git/jgit/command/remoteinfo/JGitRemoteInfoCommand.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/site/markdown/index.md.vm
src/site/site.xml

Support for public key auth for ssh transfer is added by implementing a TransportConfigCallback and adding it to the session in all JGit Commands.

[SCM-832]  maven-scm-provider-jgit should support SSH public key auth

---

maven-scm-plugin/src/test/java/org/apache/maven/scm/plugin/TagMojoTest.java

@michael-o Let's see if the test still flakes.

[SCM-936] extract common code

---

maven-scm-providers/maven-scm-provider-local/src/test/java/org/apache/maven/scm/provider/local/repository/LocalRepositoryTest.java
maven-scm-providers/maven-scm-providers-cvs/maven-scm-provider-cvs-commons/src/test/java/org/apache/maven/scm/provider/cvslib/command/changelog/CvsChangeLogConsumerTest.java
maven-scm-providers/maven-scm-providers-cvs/maven-scm-provider-cvs-commons/src/test/java/org/apache/maven/scm/provider/cvslib/repository/CvsScmProviderRepositoryTest.java
maven-scm-providers/maven-scm-providers-cvs/maven-scm-provider-cvstest/src/main/java/org/apache/maven/scm/provider/cvslib/AbstractCvsScmTest.java
maven-scm-providers/maven-scm-providers-cvs/maven-scm-provider-cvstest/src/main/java/org/apache/maven/scm/provider/cvslib/command/update/CvsUpdateCommandTest.java
maven-scm-test/src/main/java/org/apache/maven/scm/ScmTestCase.java

@michael-o turns out we don't need the getModule method at all.

[SCM-940] remove getModule method

---

maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/test/java/org/apache/maven/scm/provider/git/gitexe/command/changelog/GitChangeLogCommandTest.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/test/java/org/apache/maven/scm/provider/git/gitexe/command/status/GitStatusConsumerTest.java

[SCM-937] replace deprecated methods

---

src/site/apt/index.apt

[MNGSITE-393] remove reference to Maven 2

---

.github/workflows/maven-verify.yml

Use the new flag created with https://github.com/apache/maven-gh-actions-shared/pull/45 to install Mercurial during the CI build.

[SCM-988] Ensure Mercurial is installed in Github Actions

---

maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/pom.xml
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/main/java/org/apache/maven/scm/provider/git/jgit/command/JGitTransportConfigCallback.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/main/java/org/apache/maven/scm/provider/git/jgit/command/JGitUtils.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/main/java/org/apache/maven/scm/provider/git/jgit/command/ScmProviderAwareSshdSessionFactory.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/main/java/org/apache/maven/scm/provider/git/jgit/command/checkout/JGitCheckOutCommand.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/main/java/org/apache/maven/scm/provider/git/jgit/command/list/JGitListCommand.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/main/java/org/apache/maven/scm/provider/git/jgit/command/remoteinfo/JGitRemoteInfoCommand.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/test/java/org/apache/maven/scm/provider/git/jgit/command/checkin/JGitCheckInCommandCommitterAuthorTckTest.java

This supports OpenSSH private keys and drops usage of unmaintained JSch

[SCM-995] Upgrade JGit to 5.13.1 and leverage Apache Mina SSHD instead of JSch

---

maven-scm-plugin/pom.xml

The maven-compat is enlisted as provided dependency of plugin, while it is actually NOT needed at runtime, but due this Maven warns in 3.9.2+.
The maven-compat IS needed, but only in test scope.
---
https://issues.apache.org/jira/browse/SCM-1009

[SCM-1009] Wrong scope of maven-compat

---

maven-scm-plugin/src/main/java/org/apache/maven/scm/plugin/BootstrapMojo.java
maven-scm-providers/maven-scm-provider-hg/src/main/java/org/apache/maven/scm/provider/hg/command/tag/HgTagCommand.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/main/java/org/apache/maven/scm/provider/git/gitexe/command/branch/GitBranchCommand.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/main/java/org/apache/maven/scm/provider/git/gitexe/command/tag/GitTagCommand.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/main/java/org/apache/maven/scm/provider/git/gitexe/command/untag/GitUntagCommand.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/main/java/org/apache/maven/scm/provider/git/jgit/command/branch/JGitBranchCommand.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/main/java/org/apache/maven/scm/provider/git/jgit/command/diff/JGitDiffCommand.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/main/java/org/apache/maven/scm/provider/git/jgit/command/tag/JGitTagCommand.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/main/java/org/apache/maven/scm/provider/git/jgit/command/untag/JGitUntagCommand.java
maven-scm-providers/maven-scm-providers-svn/maven-scm-provider-svnexe/src/main/java/org/apache/maven/scm/provider/svn/svnexe/command/branch/SvnBranchCommand.java
maven-scm-providers/maven-scm-providers-svn/maven-scm-provider-svnexe/src/main/java/org/apache/maven/scm/provider/svn/svnexe/command/status/SvnStatusConsumer.java
maven-scm-providers/maven-scm-providers-svn/maven-scm-provider-svnexe/src/main/java/org/apache/maven/scm/provider/svn/svnexe/command/tag/SvnTagCommand.java

Additional replacements as compared to https://github.com/apache/maven-scm/pull/169, now also replacing where the input was trimmed.
@elharo would you mind having look at this one and a few to follow? I want to start this up again. :)

[MNG-6829] Replace trimmed StringUtils#isEmpty(String) and #isNotEmpy

---

maven-scm-api/src/main/java/org/apache/maven/scm/CommandParameter.java
maven-scm-api/src/main/java/org/apache/maven/scm/command/info/InfoItem.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/main/java/org/apache/maven/scm/provider/git/gitexe/command/info/GitInfoCommand.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/main/java/org/apache/maven/scm/provider/git/gitexe/command/info/GitInfoConsumer.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/test/java/org/apache/maven/scm/provider/git/gitexe/command/info/GitExeInfoCommandTckTest.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/test/java/org/apache/maven/scm/provider/git/gitexe/command/info/GitInfoCommandTest.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gittest/src/main/java/org/apache/maven/scm/provider/git/command/info/GitInfoCommandTckTest.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/main/java/org/apache/maven/scm/provider/git/jgit/command/JGitUtils.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/main/java/org/apache/maven/scm/provider/git/jgit/command/info/JGitInfoCommand.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/test/java/org/apache/maven/scm/provider/git/jgit/command/info/JGitInfoCommandTckTest.java
maven-scm-providers/maven-scm-providers-svn/maven-scm-provider-svnexe/src/main/java/org/apache/maven/scm/provider/svn/svnexe/command/info/SvnInfoConsumer.java
maven-scm-providers/maven-scm-providers-svn/maven-scm-provider-svnexe/src/test/java/org/apache/maven/scm/provider/svn/svnexe/command/info/SvnInfoConsumerTest.java
maven-scm-providers/maven-scm-providers-svn/maven-scm-provider-svntest/src/main/java/org/apache/maven/scm/provider/svn/command/info/SvnInfoCommandTckTest.java
maven-scm-test/src/main/java/org/apache/maven/scm/tck/command/info/InfoCommandTckTest.java

Populate it with SVN, Git and JGit for now

[SCM-914] Introduce properly typed last modified date

---

maven-scm-plugin/pom.xml

With https://issues.apache.org/jira/browse/MPLUGIN-423 the reporting mojo has been extracted in a dedicated plugin

[MNGSITE-540] Use correct plugin for reporting

---

maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/main/java/org/apache/maven/scm/provider/git/gitexe/command/GitCommandLineUtils.java
maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/main/java/org/apache/maven/scm/provider/git/gitexe/command/checkout/GitCheckOutCommand.java

When reviewing a PR I misread "cl" as an abbreviation for "change list", something that's likely to confuse anyone who's spent years working in Piper and/or Perforce.

Unabbreviate cl variable names

---

maven-scm-plugin/src/test/java/org/apache/maven/scm/plugin/ChangeLogMojoTest.java
maven-scm-plugin/src/test/java/org/apache/maven/scm/plugin/CheckoutMojoTest.java
maven-scm-plugin/src/test/java/org/apache/maven/scm/plugin/UntagMojoTest.java
maven-scm-plugin/src/test/java/org/apache/maven/scm/plugin/ValidateMojoTest.java

Asserts no longer guaranteed to pass.

Make asserts meaningful

---

maven-scm-providers/maven-scm-providers-git/maven-scm-provider-jgit/src/main/java/org/apache/maven/scm/provider/git/jgit/command/checkin/JGitCheckInCommand.java

[SCM-1029](https://issues.apache.org/jira/browse/SCM-1029)
- JGitCheckInCommand.java:
- in case of a includes / excludes FileSet is specified then:
- use OR condition of
- status.getAdded().size() > 0
- status.getChanged().size() > 0
- status.getRemoved() > 0
instead of status.hasUncommittedChanges()
- log info "nothing to commit" if nothing is to be commited
- All JUnit tests passed
- Tested in a local application

[SCM-1029] Fix empty commits on JGit checkin

---

maven-scm-plugin/src/main/java/org/apache/maven/scm/plugin/CheckoutMojo.java

Addresses #1263.
Adds an optional boolean `shallow` parameter to the checkout mojo (it is disabled by default).
When enabled, it adds `--depth 1` to the git clone command line.
Following this checklist to help us incorporate your
contribution quickly and easily:
Note that commits might be squashed by a maintainer on merge.
This may not always be possible but is a best-practice.
A more thorough check will be performed on your pull request automatically.
If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.
To make clear that you license your contribution under
the [Apache License Version 2.0, January …

Add shallow parameter to checkout mojo

---

maven-scm-plugin/src/main/java/org/apache/maven/scm/plugin/CheckLocalModificationsMojo.java
maven-scm-plugin/src/main/java/org/apache/maven/scm/plugin/TagMojo.java

The MojoExecutionException will be logged as needed. No need to double log it with an identical message

Throw is enough
